name: ci 

on:
  push:
    branches:
      -main
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: python setup
        uses: actions/setup-python@v5

      - name: install
        runs: |
          pip install -r requiremnets.txt

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_TOKEN }}

      - name: build docker
        uses: docker/build-login-action@v6
        tags: jaffysherlin/flask-app

      - name: docker image
        uses: docker image jaffysherlin/flask-app